//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.08 at 07:56:32 PM EST 
//

package net.svcret.ejb.model.registry;

import java.io.StringWriter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * <p>
 * Java class for ServiceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domain_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="service_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="versions" type="{urn:sail:proxy:registry}ServiceVersion" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(namespace = "urn:sail:proxy:registry", name = "Services")
public class Services {

	private static JAXBContext ourJaxbContext;

	@XmlElement(name="service")
	private List<Service> myServices;

	/**
	 * @return the services
	 */
	public List<Service> getServices() {
		if (myServices == null) {
			myServices = new ArrayList<Services.Service>();
		}
		return myServices;
	}
	
	public Service addService() {
		Service retVal = new Service();
		getServices().add(retVal);
		return retVal;
	}

	public String toXml() throws JAXBException {
		if (ourJaxbContext == null) {
			ourJaxbContext = JAXBContext.newInstance(Services.class);
		}

		StringWriter retVal = new StringWriter();
		Marshaller marshaller = ourJaxbContext.createMarshaller();
		marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
		marshaller.marshal(this, retVal);
		return retVal.toString();
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlRootElement(namespace = "urn:sail:proxy:registry", name = "ServiceType")
	public static class Service {

		@XmlElement(name = "domain_id", required = true)
		private String myDomainId;

		@XmlElement(name = "service_id", required = true)
		private String myServiceId;

		@XmlElement(name = "service_name", required = true)
		private String myServiceName;

		@XmlElement(name = "version")
		private Collection<ServiceVersion> myVersions;

		/**
		 * Gets the value of the domainId property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDomainId() {
			return myDomainId;
		}

		/**
		 * Gets the value of the serviceId property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getServiceId() {
			return myServiceId;
		}

		/**
		 * Gets the value of the serviceName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getServiceName() {
			return myServiceName;
		}

		/**
		 * Gets the value of the versions property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the versions property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getVersions().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link ServiceVersion }
		 * 
		 * 
		 */
		public Collection<ServiceVersion> getVersions() {
			if (myVersions == null) {
				myVersions = new ArrayList<ServiceVersion>();
			}
			return myVersions;
		}

		/**
		 * Sets the value of the domainId property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDomainId(String value) {
			this.myDomainId = value;
		}

		/**
		 * Sets the value of the serviceId property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setServiceId(String value) {
			this.myServiceId = value;
		}

		/**
		 * Sets the value of the serviceName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setServiceName(String value) {
			this.myServiceName = value;
		}
	}

}
