//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.08 at 07:56:32 PM EST 
//

package net.svcret.ejb.model.registry;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for ServiceVersion complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceVersion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dev_url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "urn:sail:proxy:registry", name = "ServiceVersion", propOrder = { "myVersionId", "myActive", "myWsdlUrl", "myUrls", "myClientAuthentication", "myServerAuthentication" })
public class ServiceVersion {

	@XmlElement(name = "client_authentication")
	private ClientAuthentication myClientAuthentication;

	@XmlElement(name = "server_authentication")
	private ServerAuthentication myServerAuthentication;

	@XmlElement(name = "url")
	private List<Url> myUrls;

	@XmlElement(name = "version_id", required = true)
	private String myVersionId;

	@XmlElement(name = "wsdl_url")
	private String myWsdlUrl;

	@XmlElement(name = "active", required=false)
	private boolean myActive;
	
	
	/**
	 * @return the active
	 */
	public boolean isActive() {
		return myActive;
	}

	/**
	 * @param theActive the active to set
	 */
	public void setActive(boolean theActive) {
		myActive = theActive;
	}

	/**
	 * @return the authentication
	 */
	public ClientAuthentication getClientAuthentication() {
		if (myClientAuthentication == null) {
			myClientAuthentication = new ClientAuthentication();
		}
		return myClientAuthentication;
	}

	/**
	 * @return the authentication
	 */
	public ServerAuthentication getServerAuthentication() {
		if (myServerAuthentication == null) {
			myServerAuthentication = new ServerAuthentication();
		}
		return myServerAuthentication;
	}

	/**
	 * Gets the value of the devUrl property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the devUrl property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDevUrl().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<Url> getUrls() {
		if (myUrls == null) {
			myUrls = new ArrayList<Url>();
		}
		return this.myUrls;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersionId() {
		return myVersionId;
	}

	/**
	 * @return the wsdlUrl
	 */
	public String getWsdlUrl() {
		return myWsdlUrl;
	}

	/**
	 * @param theAuthentication
	 *            the authentication to set
	 */
	public void setAuthentication(ClientAuthentication theAuthentication) {
		myClientAuthentication = theAuthentication;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersionId(String value) {
		this.myVersionId = value;
	}

	/**
	 * @param theWsdlUrl
	 *            the wsdlUrl to set
	 */
	public void setWsdlUrl(String theWsdlUrl) {
		myWsdlUrl = theWsdlUrl;
	}

	@XmlType(namespace = "urn:sail:proxy:registry", name = "ClientAuthentication")
	public static class ClientAuthentication {

		@XmlElements(value = { @XmlElement(name = "wssec", type = WsSecUsernameClientAuthentication.class) })
		private List<BaseClientAuthentication> myElements;

		/**
		 * @return the authentication
		 */
		public List<BaseClientAuthentication> getElements() {
			if (myElements == null) {
				myElements = new ArrayList<BaseClientAuthentication>();
			}
			return myElements;
		}

	}

	@XmlType(namespace = "urn:sail:proxy:registry", name = "ServerAuthentication")
	public static class ServerAuthentication {

		@XmlElements(value = { @XmlElement(name = "wssec", type = WsSecUsernameServerAuthentication.class) })
		private List<BaseServerAuthentication> myElements;

		/**
		 * @return the authentication
		 */
		public List<BaseServerAuthentication> getElements() {
			if (myElements == null) {
				myElements = new ArrayList<BaseServerAuthentication>();
			}
			return myElements;
		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(namespace = "urn:sail:proxy:registry", name = "Url")
	public static class Url {
		@XmlAttribute(name = "environment", required = true)
		private ServiceEnvironment myEnvironment;

		@XmlAttribute(name = "id", required = true)
		private String myId;

		@XmlValue()
		private String myUrl;

		public Url() {
			super();
		}

		public Url(ServiceEnvironment theEnvironment, String theId, String theUrl) {
			super();
			myEnvironment = theEnvironment;
			myId = theId;
			myUrl = theUrl;
		}

		/**
		 * @return the environment
		 */
		public ServiceEnvironment getEnvironment() {
			return myEnvironment;
		}

		/**
		 * @return the id
		 */
		public String getId() {
			return myId;
		}

		/**
		 * @return the url
		 */
		public String getUrl() {
			return myUrl;
		}

		/**
		 * @param theEnvironment
		 *            the environment to set
		 */
		public void setEnvironment(ServiceEnvironment theEnvironment) {
			myEnvironment = theEnvironment;
		}

		/**
		 * @param theId
		 *            the id to set
		 */
		public void setId(String theId) {
			myId = theId;
		}

		/**
		 * @param theUrl
		 *            the url to set
		 */
		public void setUrl(String theUrl) {
			myUrl = theUrl;
		}
	}

}
